name: CI test

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo checkout!

      - name: Check out develop branch
        run: git checkout develop
        if: github.ref == 'refs/heads/develop'
