name: CI

on:
  push:
    branches:
      - master
      - developer

  pull_request:
    branches:
      - master
      - developer

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Build with Gradle
        run: |
          ./gradlew :app:build
          
      - name: Check status
        run: echo "Check build status"
      - name: Set failed if build failed
        if: failure()
        run: |
          echo "::error::Build failed"
