name: CI

on:
  push:
    branches:
      - master
      - developer
  pull_request:
    branches:
      - master
      - developer
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo checkout!

      - name: Check out developer branch
        run: git checkout developer
        if: github.ref == 'refs/heads/developer'
